# Generated by Django 4.1.7 on 2023-12-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enrollment_number', models.IntegerField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('course', models.CharField(max_length=256)),
                ('semester', models.IntegerField(unique=True)),
                ('club', models.CharField(max_length=256)),
            ],
        ),
    ]
