# Generated by Django 4.1.7 on 2023-12-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_club_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='enrollment_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
