# Generated by Django 4.1.7 on 2023-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_members_email_alter_members_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='club',
            field=models.CharField(choices=[('Technical', 'Technical club'), ('Sports', 'Sports club'), ('Cultural', 'Cultural club'), ('Eco', 'Eco club')], max_length=256),
        ),
        migrations.AlterField(
            model_name='members',
            name='course',
            field=models.CharField(choices=[('BCA - Bachelor Of Computer Application', 'BCA - Bachelor Of Computer Application'), ('MCA - Master Of Computer Application', 'MCA - Master Of Computer Application')], max_length=256),
        ),
        migrations.AlterField(
            model_name='members',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=256),
        ),
    ]
